#!/bin/bash
cd ~/OrangeFox
  source build/envsetup.sh
export ALLOW_MISSING_DEPENDENCIES=true
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export LC_ALL="C"
lunch omni_TBX304-eng
mka recoveryimage
sudo su
curl --upload-file /out/target/product/TBX304/OrangeFox-Unofficial-X00P.zip
curl --upload-file ./out/target/product/TBX304/OrangeFox-Unofficial-X00P.zip
curl --upload-file out/target/product/TBX304/OrangeFox-Unofficial-X00P.zip
cd ~/OrangeFox
curl --upload-file /out/target/product/TBX304/OrangeFox-U>
curl --upload-file ./out/target/product/TBX304/OrangeFox->
curl --upload-file out/target/product/TBX304/OrangeFox-Un>

echo "/nUploaded All files successfully!"
