#!/bin/bash
cd ~/OrangeFox_10/fox_10.0
  source build/envsetup.sh
export ALLOW_MISSING_DEPENDENCIES=true
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export LC_ALL="C"
lunch omni_shiva-eng
mka recoveryimage
curl --upload-file ./out/target/product/shiva/OrangeFox-unofficial-shiva.img http://transfer.sh/
echo "/nUploaded All files successfully!"
