#!/bin/bash

url=https://cheems.mirrorbomt.workers.dev/0:/lineage-ccache.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf lineage-ccache.tar.gz
echo "unzip done"
find lineage-ccache.tar.gz -delete
