#!/bin/bash

url=http://transfer.sh/1cZAfEU/ccache-example.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf lineage-ccache.tar.gz
echo "unzip done"
find lineage-ccache.tar.gz -delete
