#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
repo init --depth 1 -u https://github.com/crdroidandroid/android -b 9.0
git clone https://github.com/Raddagast/android_device_lenovo_TBX304 device/lenovo/TBX304
git clone https://github.com/Raddagast/android_device_lenovo_tb-common device/lenovo/
git clone https://github.com/lenovo-devs/proprietary_vendor_lenovo -b lineage-16.0-msm8937 vendor/lenovo

repo sync
ls


