#!/bin/bash
cd ~
sudo apt install git aria2 -y
git clone https://gitlab.com/OrangeFox/misc/scripts
cd scripts
sudo bash setup/android_build_env.sh
sudo bash setup/install_android_sdk.sh
mkdir ~/OrangeFox_10
repo init -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-10.0
repo sync
pwd
ls
cd ~/OrangeFox_10/fox_10.0
##delete these lines, and replace with your own lines of device sauce
git clone https://github.com/Kingler04ak/twrp_xiaomi_merlin device/xiaomi/merlin
