#!/bin/bash
mkdir ~/OrangeFox
cd ~/OrangeFox
git clone https://github.com/lenovo-devs/android_device_lenovo_TBX304 device/lenovo/TBX304
git clone https://github.com/lenovo-devs/android_device_lenovo_tb-common -b lineage-16.0-msm8937 device/lenovo/tb-common
git clone https://github.com/lenovo-devs/android_kernel_lenovo_msm8953 -b lineage-16.0-tbx304 kernel/lenovo/msm8953
git clone https://github.com/lenovo-devs/proprietary_vendor_lenovo -b lineage-16.0-msm8937 vendor/lenovo/
repo init -u git://github.com/LineageOS/android.git -b lineage-15.0
repo sync

. build/envsetup.sh
lunch lineage_TBX304-userdebug
mka bacon
